export const appRoutes = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  admissions: "/dashboard/admissions",
  newAdmission: "/dashboard/admissions/new",
  admissionDetails: (admissionId: string) => `/dashboard/admissions/${admissionId}`,
  students: "/dashboard/students",
  studentDetails: (studentId: string) => `/dashboard/students/${studentId}`,
  academic: "/dashboard/academic",
  academicYears: "/dashboard/academic/years",
  academicGradeLevels: "/dashboard/academic/grade-levels",
  academicClasses: "/dashboard/academic/classes",
  academicSubjects: "/dashboard/academic/subjects",
  academicEnrollments: "/dashboard/academic/enrollments",
  attendance: "/dashboard/attendance",
  attendanceSessions: "/dashboard/attendance/sessions",
  newAttendanceSession: "/dashboard/attendance/sessions/new",
  attendanceSessionDetails: (sessionId: string) =>
    `/dashboard/attendance/sessions/${sessionId}`,
  attendanceExcuses: "/dashboard/attendance/excuses",
  grades: "/dashboard/grades",
  gradesExams: "/dashboard/grades/exams",
  newGradesExam: "/dashboard/grades/exams/new",
  gradesExamDetails: (examId: string) => `/dashboard/grades/exams/${examId}`,
  gradeEntries: "/dashboard/grades/entries",
  reportCards: "/dashboard/grades/report-cards",
  reportCardDetails: (reportCardId: string) =>
    `/dashboard/grades/report-cards/${reportCardId}`,
  timetable: "/dashboard/timetable",
  timetableRooms: "/dashboard/timetable/rooms",
  timetableAssignments: "/dashboard/timetable/assignments",
  timetableSlots: "/dashboard/timetable/slots",
  newTimetableSlot: "/dashboard/timetable/slots/new",
} as const
