export const appRoutes = {
  home: "/",
  login: "/login",
  dashboard: "/dashboard",
  admissions: "/dashboard/admissions",
  newAdmission: "/dashboard/admissions/new",
  admissionDetails: (admissionId: string) => `/dashboard/admissions/${admissionId}`,
  students: "/dashboard/students",
  studentDetails: (studentId: string) => `/dashboard/students/${studentId}`,
  academic: "/dashboard/academic",
  academicYears: "/dashboard/academic/years",
  academicGradeLevels: "/dashboard/academic/grade-levels",
  academicClasses: "/dashboard/academic/classes",
  academicSubjects: "/dashboard/academic/subjects",
  academicEnrollments: "/dashboard/academic/enrollments",
  attendance: "/dashboard/attendance",
  attendanceSessions: "/dashboard/attendance/sessions",
  newAttendanceSession: "/dashboard/attendance/sessions/new",
  attendanceSessionDetails: (sessionId: string) =>
    `/dashboard/attendance/sessions/${sessionId}`,
  attendanceExcuses: "/dashboard/attendance/excuses",
  grades: "/dashboard/grades",
  gradesExams: "/dashboard/grades/exams",
  newGradesExam: "/dashboard/grades/exams/new",
  gradesExamDetails: (examId: string) => `/dashboard/grades/exams/${examId}`,
  gradeEntries: "/dashboard/grades/entries",
  reportCards: "/dashboard/grades/report-cards",
  reportCardDetails: (reportCardId: string) =>
    `/dashboard/grades/report-cards/${reportCardId}`,
  timetable: "/dashboard/timetable",
  timetableRooms: "/dashboard/timetable/rooms",
  timetableAssignments: "/dashboard/timetable/assignments",
  timetableSlots: "/dashboard/timetable/slots",
  newTimetableSlot: "/dashboard/timetable/slots/new",
  finance: "/dashboard/finance",
  financeFees: "/dashboard/finance/fees",
  financeDiscounts: "/dashboard/finance/discounts",
  financeInvoices: "/dashboard/finance/invoices",
  newFinanceInvoice: "/dashboard/finance/invoices/new",
  financeInvoiceDetails: (invoiceId: string) =>
    `/dashboard/finance/invoices/${invoiceId}`,
  financePayments: "/dashboard/finance/payments",
  financePaymentDetails: (paymentId: string) =>
    `/dashboard/finance/payments/${paymentId}`,
  communication: "/dashboard/communication",
  communicationMessages: "/dashboard/communication/messages",
  newCommunicationMessage: "/dashboard/communication/messages/new",
  communicationMessageDetails: (messageId: string) =>
    `/dashboard/communication/messages/${messageId}`,
  communicationAnnouncements: "/dashboard/communication/announcements",
  newCommunicationAnnouncement: "/dashboard/communication/announcements/new",
  communicationEvents: "/dashboard/communication/events",
  newCommunicationEvent: "/dashboard/communication/events/new",
  communicationNotifications: "/dashboard/communication/notifications",
  reports: "/dashboard/reports",
  reportsStudents: "/dashboard/reports/students",
  reportsAttendance: "/dashboard/reports/attendance",
  reportsGrades: "/dashboard/reports/grades",
  reportsFinance: "/dashboard/reports/finance",
  reportsTimetable: "/dashboard/reports/timetable",
} as const
