export const appRoutes = {
  home: "/",
  login: "/login",
  loginStaff: "/login/staff",
  loginPortal: "/login/portal",
  loginResetPassword: "/login/reset-password",
  dashboard: "/dashboard",
  portal: "/portal",
  portalStudents: "/portal/students",
  portalStudentDetails: (studentId: string) => `/portal/students/${studentId}`,
  portalAttendance: "/portal/attendance",
  portalGrades: "/portal/grades",
  portalTimetable: "/portal/timetable",
  portalFinance: "/portal/finance",
  portalLibrary: "/portal/library",
  portalAnnouncements: "/portal/announcements",
  portalChat: "/portal/chat",
  portalAssistant: "/portal/assistant",
  portalProfile: "/portal/profile",
  admissions: "/dashboard/admissions",
  newAdmission: "/dashboard/admissions/new",
  admissionDetails: (admissionId: string) => `/dashboard/admissions/${admissionId}`,
  students: "/dashboard/students",
  studentDetails: (studentId: string) => `/dashboard/students/${studentId}`,
  academic: "/dashboard/academic",
  academicYears: "/dashboard/academic/years",
  academicGradeLevels: "/dashboard/academic/grade-levels",
  academicClasses: "/dashboard/academic/classes",
  academicSubjects: "/dashboard/academic/subjects",
  academicEnrollments: "/dashboard/academic/enrollments",
  attendance: "/dashboard/attendance",
  attendanceSessions: "/dashboard/attendance/sessions",
  newAttendanceSession: "/dashboard/attendance/sessions/new",
  attendanceSessionDetails: (sessionId: string) =>
    `/dashboard/attendance/sessions/${sessionId}`,
  attendanceExcuses: "/dashboard/attendance/excuses",
  grades: "/dashboard/grades",
  gradesExams: "/dashboard/grades/exams",
  newGradesExam: "/dashboard/grades/exams/new",
  gradesExamDetails: (examId: string) => `/dashboard/grades/exams/${examId}`,
  gradeEntries: "/dashboard/grades/entries",
  reportCards: "/dashboard/grades/report-cards",
  reportCardDetails: (reportCardId: string) =>
    `/dashboard/grades/report-cards/${reportCardId}`,
  timetable: "/dashboard/timetable",
  timetableRooms: "/dashboard/timetable/rooms",
  timetableAssignments: "/dashboard/timetable/assignments",
  timetableSlots: "/dashboard/timetable/slots",
  newTimetableSlot: "/dashboard/timetable/slots/new",
  finance: "/dashboard/finance",
  financeFees: "/dashboard/finance/fees",
  financeDiscounts: "/dashboard/finance/discounts",
  financeInvoices: "/dashboard/finance/invoices",
  newFinanceInvoice: "/dashboard/finance/invoices/new",
  financeInvoiceDetails: (invoiceId: string) =>
    `/dashboard/finance/invoices/${invoiceId}`,
  financePayments: "/dashboard/finance/payments",
  financePaymentDetails: (paymentId: string) =>
    `/dashboard/finance/payments/${paymentId}`,
  communication: "/dashboard/communication",
  communicationMessages: "/dashboard/communication/messages",
  newCommunicationMessage: "/dashboard/communication/messages/new",
  communicationMessageDetails: (messageId: string) =>
    `/dashboard/communication/messages/${messageId}`,
  communicationAnnouncements: "/dashboard/communication/announcements",
  newCommunicationAnnouncement: "/dashboard/communication/announcements/new",
  communicationEvents: "/dashboard/communication/events",
  newCommunicationEvent: "/dashboard/communication/events/new",
  communicationNotifications: "/dashboard/communication/notifications",
  feedback: "/dashboard/feedback",
  feedbackComplaints: "/dashboard/feedback/complaints",
  newFeedbackComplaint: "/dashboard/feedback/complaints/new",
  feedbackComplaintDetails: (complaintId: string) =>
    `/dashboard/feedback/complaints/${complaintId}`,
  feedbackSurveys: "/dashboard/feedback/surveys",
  newFeedbackSurvey: "/dashboard/feedback/surveys/new",
  feedbackSurveyDetails: (surveyId: string) => `/dashboard/feedback/surveys/${surveyId}`,
  feedbackSurveyRespond: (surveyId: string) =>
    `/dashboard/feedback/surveys/${surveyId}/respond`,
  feedbackSurveyResponses: (surveyId: string) =>
    `/dashboard/feedback/surveys/${surveyId}/responses`,
  reports: "/dashboard/reports",
  reportsStudents: "/dashboard/reports/students",
  reportsAttendance: "/dashboard/reports/attendance",
  reportsGrades: "/dashboard/reports/grades",
  reportsFinance: "/dashboard/reports/finance",
  reportsTimetable: "/dashboard/reports/timetable",
  settings: "/dashboard/settings",
  settingsSchool: "/dashboard/settings/school",
  settingsBranding: "/dashboard/settings/branding",
  settingsLocalization: "/dashboard/settings/localization",
  settingsModules: "/dashboard/settings/modules",
  settingsTemplates: "/dashboard/settings/templates",
  integrations: "/dashboard/integrations",
  integrationsWhatsapp: "/dashboard/integrations/whatsapp",
  integrationsWebhooks: "/dashboard/integrations/webhooks",
  integrationsMoe: "/dashboard/integrations/moe",
  integrationsCalendar: "/dashboard/integrations/calendar",
  integrationsBi: "/dashboard/integrations/bi",
  integrationsAutomation: "/dashboard/integrations/automation",
  studentCare: "/dashboard/student-care",
  studentCareHealth: "/dashboard/student-care/health",
  studentCareHealthDetails: (studentId: string) =>
    `/dashboard/student-care/health/${studentId}`,
  studentCareVaccinations: "/dashboard/student-care/vaccinations",
  studentCareClinicVisits: "/dashboard/student-care/clinic-visits",
  newStudentCareClinicVisit: "/dashboard/student-care/clinic-visits/new",
  studentCareDiscipline: "/dashboard/student-care/discipline",
  newStudentCareDiscipline: "/dashboard/student-care/discipline/new",
  studentCareAchievements: "/dashboard/student-care/achievements",
  newStudentCareAchievement: "/dashboard/student-care/achievements/new",
  library: "/dashboard/library",
  libraryCatalog: "/dashboard/library/catalog",
  newLibraryCatalog: "/dashboard/library/catalog/new",
  libraryCatalogDetails: (catalogId: string) =>
    `/dashboard/library/catalog/${catalogId}`,
  libraryCopies: "/dashboard/library/copies",
  newLibraryCopy: "/dashboard/library/copies/new",
  libraryLoans: "/dashboard/library/loans",
  newLibraryLoan: "/dashboard/library/loans/new",
  libraryLoanDetails: (loanId: string) => `/dashboard/library/loans/${loanId}`,
  libraryOverdue: "/dashboard/library/overdue",
  dashboardChat: "/dashboard/chat",
  dashboardAssistant: "/dashboard/assistant",
} as const
